name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build release binaries
      env:
        VERSION: ${{ github.ref_name }}
        COMMIT: ${{ github.sha }}
        DATE: ${{ github.event.head_commit.timestamp }}
      run: |
        ./scripts/build.sh
    
    - name: Generate release notes
      id: release_notes
      run: |
        # Get the tag message or generate from commits
        TAG_MESSAGE=$(git tag -l --format='%(contents)' ${{ github.ref_name }})
        
        if [ -z "$TAG_MESSAGE" ]; then
          # Generate from commits since last tag
          LAST_TAG=$(git tag --sort=-version:refname | head -2 | tail -1)
          if [ -n "$LAST_TAG" ]; then
            COMMITS=$(git log --pretty=format:"- %s" ${LAST_TAG}..HEAD)
            RELEASE_NOTES="## Changes\n\n${COMMITS}"
          else
            RELEASE_NOTES="## Release ${{ github.ref_name }}\n\nInitial release of kportforward Go version."
          fi
        else
          RELEASE_NOTES="$TAG_MESSAGE"
        fi
        
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
        echo -e "$RELEASE_NOTES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ${{ steps.release_notes.outputs.RELEASE_NOTES }}
          
          ## Installation
          
          Download the appropriate binary for your platform:
          
          - **macOS (Intel)**: `kportforward-darwin-amd64`
          - **macOS (Apple Silicon)**: `kportforward-darwin-arm64`
          - **Linux**: `kportforward-linux-amd64`
          - **Windows**: `kportforward-windows-amd64.exe`
          
          Make the binary executable and place it in your PATH:
          
          ```bash
          chmod +x kportforward-*
          sudo mv kportforward-* /usr/local/bin/kportforward
          ```
          
          ## Features
          
          - 🚀 Modern terminal UI with real-time updates
          - 🔄 Automatic port-forward recovery and monitoring
          - 🌐 Cross-platform support (macOS, Linux, Windows)
          - 📊 Interactive sorting and service details
          - 🔧 Embedded configuration with user overrides
          - 🆙 Built-in auto-update system
          - 🎯 gRPC UI and Swagger UI integration
          
          ## Checksums
          
          Verify your download with the checksums below.
        files: |
          dist/*
        draft: false
        prerelease: false
    
    - name: Update latest tag
      run: |
        git tag -f latest
        git push origin latest --force